/**
 * @file invoicesApi.ts
 * @description Real-backend API layer for /api/Invoices. READ-ONLY — no
 * create/update/delete (invoices are generated by the backend, not admins).
 *
 * Envelope-aware: `{ success, message, data:{ items[], pageNumber, pageSize,
 * totalCount, totalPages }, errors }` — `data` IS the page. Mirrors the
 * `unwrap()` / `fromRawPage()` pattern from
 * src/modules/orders/api/ordersApi.ts (kept as a local mirror rather than a
 * shared extraction — the two adapters differ in defaults and may diverge).
 *
 * LIVE-CONFIRMED (2026-09-03): list and detail return an IDENTICAL
 * `InvoiceResponseDto` of exactly four fields. Query params PageNumber,
 * PageSize (1–100), SortBy, SortDescending, FromDate, ToDate are accepted; a
 * bad SortBy/FilterBy returns HTTP 400. A missing id on GET /{id} returns a
 * not-found business error (`success: false`).
 */
import { apiClient } from "@shared/lib/axios";
import type { PaginatedResponse } from "@shared/types/api";
import type { ApiEnvelope } from "@modules/services/lib/categoryAdapter";
import type { Invoice, InvoicesListParams, RawInvoice } from "../types";
import { invoiceCode } from "../lib/invoiceCode";

interface RawPage<T> {
  items: T[];
  pageNumber: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
}

const DEFAULT_PAGE_SIZE = 20;
const MAX_PAGE_SIZE = 100;

function unwrap<T>(envelope: ApiEnvelope<T>): T {
  if (!envelope.success) throw new Error(envelope.message || "Request failed");
  return envelope.data;
}

function fromRawPage<T>(page: RawPage<T> | T[] | null | undefined): PaginatedResponse<T> {
  if (!page) {
    return { items: [], page: 1, pageSize: DEFAULT_PAGE_SIZE, total: 0, totalPages: 0 };
  }
  if (Array.isArray(page)) {
    return {
      items: page,
      page: 1,
      pageSize: DEFAULT_PAGE_SIZE,
      total: page.length,
      totalPages: page.length ? 1 : 0,
    };
  }
  return {
    items: page.items ?? [],
    page: page.pageNumber,
    pageSize: page.pageSize,
    total: page.totalCount,
    totalPages: page.totalPages,
  };
}

/** Thin raw→view adapter. `createdAt` is passed through as-is (local ISO). */
export function adaptRawInvoice(raw: RawInvoice): Invoice {
  return {
    id: String(raw.id),
    code: invoiceCode(raw.id),
    fullName: raw.fullName,
    totalPrice: raw.totalPrice,
    createdAt: raw.createdAt,
  };
}

export const invoicesApi = {
  list: async (params: InvoicesListParams = {}): Promise<PaginatedResponse<RawInvoice>> => {
    const { data } = await apiClient.get<ApiEnvelope<RawPage<RawInvoice> | RawInvoice[] | null>>(
      "/Invoices",
      {
        params: {
          PageNumber: params.pageNumber ?? 1,
          PageSize: Math.min(params.pageSize ?? DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE),
          SortBy: params.sortBy,
          SortDescending: params.sortDescending,
          FromDate: params.fromDate,
          ToDate: params.toDate,
        },
      },
    );
    return fromRawPage(unwrap(data));
  },

  get: async (id: string): Promise<RawInvoice> => {
    const { data } = await apiClient.get<ApiEnvelope<RawInvoice>>(`/Invoices/${id}`);
    return unwrap(data);
  },
};
