name: Notify Discord On Main Commit

on:
  push:
    branches:
      - main

jobs:
  discord-notification:

    runs-on: ubuntu-latest

    steps:

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "username": "GitHub Bot",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "content": "🚀 New commit pushed to main branch!"
          }' \
          $DISCORD_WEBHOOK
